#pragma once

#ifdef EELIBRARY_EXPORTS
#define EELIBRARY_API __declspec(dllexport)
#else
#define EELIBRARY_API __declspec(dllimport)
#endif

#define EELIBRARY_VERSION_MAJOR 1
#define EELIBRARY_VERSION_MINOR 0
#define EELIBRARY_VERSION_PATCH 0

#define EELIBRARY_LAST_COMPATIBLE_VERSION_MAJOR 1
#define EELIBRARY_LAST_COMPATIBLE_VERSION_MINOR 0
#define EELIBRARY_LAST_COMPATIBLE_VERSION_PATCH 0

/*
	No changes should be needed below this line.
	============================================
*/

#ifndef STRINGIFY
	#define STRINGIFY(x) #x
#endif // !STRINGIFY

#define EELIBRARY_VERSION_STRING STRINGIFY(EELIBRARY_VERSION_MAJOR) "." STRINGIFY(EELIBRARY_VERSION_MINOR) "." STRINGIFY(EELIBRARY_VERSION_PATCH)
#define EELIBRARY_LAST_COMPATIBLE_VERSION_STRING STRINGIFY(EELIBRARY_LAST_COMPATIBLE_VERSION_MAJOR) "." STRINGIFY(EELIBRARY_LAST_COMPATIBLE_VERSION_MINOR) "." STRINGIFY(EELIBRARY_LAST_COMPATIBLE_VERSION_PATCH)

#if EELIBRARY_VERSION_MAJOR > 255 || EELIBRARY_VERSION_MINOR > 255 || EELIBRARY_VERSION_PATCH > 255
	#error "EELIBRARY_VERSION_MAJOR, EELIBRARY_VERSION_MINOR and EELIBRARY_VERSION_PATCH must be less than 256."
#endif

#if EELIBRARY_LAST_COMPATIBLE_VERSION_MAJOR > 255 || EELIBRARY_LAST_COMPATIBLE_VERSION_MINOR > 255 || EELIBRARY_LAST_COMPATIBLE_VERSION_PATCH > 255
	#error "EELIBRARY_LAST_COMPATIBLE_VERSION_MAJOR, EELIBRARY_LAST_COMPATIBLE_VERSION_MINOR and EELIBRARY_LAST_COMPATIBLE_VERSION_PATCH must be less than 256."
#endif

#define EELIBRARY_VERSION ((EELIBRARY_VERSION_MAJOR << 16) | (EELIBRARY_VERSION_MINOR << 8) | EELIBRARY_VERSION_PATCH)

// Used to check if a mod is compatible with the current version of EE Library.
// If the version is not compatible, the mod will not be loaded.
#define EELIBRARY_LAST_COMPATIBLE_VERSION ((EELIBRARY_LAST_COMPATIBLE_VERSION_MAJOR << 16) | (EELIBRARY_LAST_COMPATIBLE_VERSION_MINOR << 8) | EELIBRARY_LAST_COMPATIBLE_VERSION_PATCH)

#define EELIBRARY_OK 0
#define EELIBRARY_ERROR 1
